import type { Locale } from '@/i18n/dictionaries';

export const siteContent = {
  en: {
    global: {
      footerLabel: 'PALAIS DES CHIMÈRES — VID’MY',
      websiteBy: 'Website by',
      shipping: 'Shipping & Returns',
      archive: 'Archive',
      terms: 'Terms',
      privacy: 'Privacy',
      mobileShipping: 'Shipping',
      mobileTerms: 'Terms',
      mobilePrivacy: 'Privacy',
      openNavigation: 'Open navigation',
      closeNavigation: 'Close navigation',
      mobileFooter: 'Palais des Chimères — VID’MY 2027',
      nav: {
        home: 'HOME',
        collection: 'COLLECTION',
        film: 'FILM',
        about: 'ABOUT',
        contact: 'CONTACT',
      },
    },
    home: {
      heroAlt: 'Palais des Chimères — VID’MY 2027 F/W',
      collectionLine: 'VID’MY — 2027',
    },
    collection: {
      title: 'COLLECTION',
      collectionLine: 'VID’MY — 2027',
      intro: 'Put on a different skin. See the world through a new form.',
      jewelryName: 'Jewelry',
      jewelryMeta: 'Coming soon',
      cards: {
        'veil-of-becoming': { displayName: 'RED WITCH', displayMeta: '€1,300' },
        'chimera-form': { displayName: 'KOZA', displayMeta: '€2,570' },
        'ivory-bloom': { displayName: 'VAZA', displayMeta: '€4,500' },
        'blood-current': { displayName: 'Black witch', displayMeta: '€1,450' },
        'nocturne-creature': { displayName: 'The CAT', displayMeta: '€1,200' },
      },
    },
    archive: {
      title: 'ARCHIVE',
      collectionLine: 'VID’MY — 2027',
      intro: 'A record of complete looks and individual pieces from the collection.',
    },
    contact: {
      eyebrow: 'Get in touch with us',
      titleLine1: 'Contact the brand',
      titleLine2: '',
      intro: 'For collaborations, custom pieces, editorial requests or private appointments, we would love to hear from you.',
      email: 'contact@palaisdeschimeres.com',
      imageAlt: 'Palais des Chimères editorial portrait',
      portfolio: 'View selected work',
      formSubmit: 'SEND INQUIRY',
    },
    film: {
      eyebrow: 'FASHION FILM',
      titleLine1: 'VID’MY',
      titleLine2: '—',
      subtitle: 'A fashion film by Palais des Chimères.',
      director: 'Diana Vyshnevetska',
      collection: 'VID’MY — 2027',
      year: '2027',
      video: 'Sviatoslav Opryshko',
      posterAlt: 'VID’MY — Fashion Film Poster',
      modalAria: 'Fashion Film Player',
      modalClose: 'Close film player',
      iframeTitle: 'VID’MY — Fashion Film by Palais des Chimères',
      modalCollection: '2027',
    },
  },
  fr: {
    global: {
      footerLabel: 'PALAIS DES CHIMÈRES — VID’MY',
      websiteBy: 'Site par',
      shipping: 'Livraison et retours',
      archive: 'Archives',
      terms: 'Conditions',
      privacy: 'Confidentialité',
      mobileShipping: 'Livraison',
      mobileTerms: 'Conditions',
      mobilePrivacy: 'Confidentialité',
      openNavigation: 'Ouvrir la navigation',
      closeNavigation: 'Fermer la navigation',
      mobileFooter: 'Palais des Chimères — VID’MY 2027',
      nav: {
        home: 'ACCUEIL',
        collection: 'COLLECTION',
        film: 'FILM',
        about: 'À PROPOS',
        contact: 'CONTACT',
      },
    },
    home: {
      heroAlt: 'Palais des Chimères — VID’MY 2027 Automne/Hiver',
      collectionLine: 'VID’MY — 2027',
    },
    collection: {
      title: 'COLLECTION',
      collectionLine: 'VID’MY — 2027',
      intro: 'Revêtez une autre peau. Regardez le monde à travers une nouvelle forme.',
      jewelryName: 'Bijoux',
      jewelryMeta: 'Bientôt disponible',
      cards: {
        'veil-of-becoming': { displayName: 'SORCIÈRE ROUGE', displayMeta: '1 300 €' },
        'chimera-form': { displayName: 'KOZA', displayMeta: '2 570 €' },
        'ivory-bloom': { displayName: 'VAZA', displayMeta: '4 500 €' },
        'blood-current': { displayName: 'SORCIÈRE NOIRE', displayMeta: '1 450 €' },
        'nocturne-creature': { displayName: 'LE CHAT', displayMeta: '1 200 €' },
      },
    },
    archive: {
      title: 'ARCHIVES',
      collectionLine: 'VID’MY — 2027',
      intro: 'Un répertoire des looks complets et des pièces individuelles de la collection.',
    },
    contact: {
      eyebrow: 'Contactez-nous',
      titleLine1: 'Contacter la marque',
      titleLine2: '',
      intro: 'Pour les collaborations, les pièces sur mesure, les demandes éditoriales ou les rendez-vous privés, nous serions ravis de vous entendre.',
      email: 'contact@palaisdeschimeres.com',
      imageAlt: 'Portrait éditorial de Palais des Chimères',
      portfolio: 'Voir une sélection de travaux',
      formSubmit: 'ENVOYER UNE DEMANDE',
    },
    film: {
      eyebrow: 'FILM DE MODE',
      titleLine1: 'VID’MY',
      titleLine2: '—',
      subtitle: 'Un film de mode par Palais des Chimères.',
      director: 'Diana Vyshnevetska',
      collection: 'VID’MY — 2027',
      year: '2027',
      video: 'Sviatoslav Opryshko',
      posterAlt: 'VID’MY — Affiche du film de mode',
      modalAria: 'Lecteur du film de mode',
      modalClose: 'Fermer le lecteur du film',
      iframeTitle: 'VID’MY — Film de mode par Palais des Chimères',
      modalCollection: '2027',
    },
  },
} as const;

export function getSiteContent(locale: string) {
  return siteContent[(locale as Locale) in siteContent ? (locale as Locale) : 'en'];
}
